build:
  version: 2.0

cards:
  message: "Welcome to BrandonBank cards related QA APIs "
  contactDetails:
    name: "John Top - QA Lead"
    email: "john@brownsbank.com"
  onCallSupport:
    - (555) 323-1234
    - (555) 543-1345